apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-html
  labels:
    app: {{ .Chart.Name }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>BIGAP Test App</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
            }
            .container {
                text-align: center;
                padding: 40px;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 20px;
                backdrop-filter: blur(10px);
            }
            h1 {
                font-size: 3em;
                margin-bottom: 20px;
            }
            p {
                font-size: 1.2em;
            }
            .badge {
                display: inline-block;
                padding: 10px 20px;
                margin: 10px;
                background: rgba(255, 255, 255, 0.2);
                border-radius: 10px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>BIGAP Test Application</h1>
            <p>Deployed via ArgoCD + GitOps</p>
            <div class="badge">Environment: DEV</div>
            <div class="badge">Version: 1.0</div>
        </div>
    </body>
    </html>
