# ExternalSecret for S3 backup credentials
# This secret is required by the PostgreSQL operator to backup to S3
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-db-pgbackrest-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: {{ .Chart.Name }}-db-pgbackrest-secrets

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: secret/{{ .Values.environment }}/s3-backup
        property: access_key

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/{{ .Values.environment }}/s3-backup
        property: secret_key
