replicaCount: 1

environment: dev  # Override in ApplicationSet for prod

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.25-alpine"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  # Hostname will be: test-app.{environment}.bigap.fr
  domain: bigap.fr
  hosts:
    - host: test-app.dev.bigap.fr  # Default for dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - test-app.dev.bigap.fr  # Default for dev

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
